@startuml
hide empty description

[*] -> タイトルメニュー

タイトルメニュー --> ゲームプレイ
ゲームプレイ --> ゲームプレイ : 次ステージへ
ゲームプレイ --> ゲームオーバーメニュー
ゲームオーバーメニュー --> タイトルメニュー : タイトルへ
ゲームオーバーメニュー --> ゲームプレイ : リトライ
ゲームプレイ --> クレジット : ゲームクリア
クレジット --> タイトルメニュー

@enduml
